[project]
name = "explainable-brains-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "anthropic",
    "pandas",
    "python-dotenv",
    "pydantic",
]

[tool.vercel]
entrypoint = "chat_server:app"
